---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgDMi3xpCKV3FT8JUYwFWUqFykdMlrB/dwNmRkSTN93qVr87ydn/xw4EvgjkBqbB8Mp+Je3kz3UGtQWEkljDLGpqfcnN7xF+hN3cTmMeLdzhVD57F+pT1EevsXY43Fwiktgh1lYDZsWuGrnSaZgtB8KUjlomxKX75/IFUFDU6oCh7QEeLDL3zWZdjto+ibbe9g9bDNv2Mrmo+DU6kOUnkUZN+YN9Vg9rxZcW0zYODm/I0mugecifLTMgX/trKEeDdhOWS3LbYZQQsvL/v9/cRJy69rbsswIMNmYePophm+dROQYEjEt4aGG9dbs9DDGMAVvCTesZzc8ap/Sdp9JkBCl6LGXnAHuox15O6DqF5/jCLMF00qfHYqbcsherhmASXX1lVfRH8IjApbpWY2WLhtKcp1pEjcIb0nBA1ANeG6nqbXVyJNWAupNBGBcY8qq2Y+ajlBPDDB/zUeV4xJIa8k6cdG3ahEjJbGnx6zFJkMc6ERdY0SAQ3p8YgSsLZPArxeA/L0hidyXFcA38FobngAf828JoKbS9oLhhR1sEU28cHXzeIGEEEr3jDdtWZRyZMKZfTmhDZu+AkX6gghziaBHke4NfBw13YnLJwSJWzXniEh9CqHHC11C81HNdKUEFC0gJhjKqn5/Vj7N01lMmzR4lz0voTpWi2kDI+eGxMAptzzQtFIa/65bk7olNlbOC1S72jMtm5XHMe/Mbq2WuVvKcAlRi7JgujEBlWwZ+6B/T5Gaerd9jYeoO
  template:
    metadata:
      name: github-oauth-client-secret
      namespace: openshift-config
