---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oauth-client-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCjpfZ/bzS/1pvrbSImpAWuNIDuqd0M4/IPKZGdT7reD+HEoEpE66aEQ/YhI7uo+e9lKSCXIHhrdpT0I+Gy4aINtE5gcuGXItx5i2y4dioqxCn5oIqUiZg4nCJo/TxTi6B2bjJ9DtSf/rq1uoW9a5nm1poEXrE+TEYn9Y83/vrrZEImJjD2c8BIJz4XPCTcdj/oakOcsOGy654HD9XV5QNOlnAQenpecJWVSdlGgbZspdidyc3tTRkwwvuP8id1MiM5zcmDDqOssuJNibZaWUJu8L9B1lhIbtgUijK2efyYOtIyQB5p1nPRrJdcUI/Lw2JR2qZqbRRB2WiMbv3vchdi6h3WNpWm4w8atmHbZlhYwKMklCJJ4N/S2lMfVfpanntvm5PfNhex9oswJXGhvv6I74KRkVOjmrYcr8uiGwcl7n64PLt0bscdNdx+/bl8QdaIcvx8Ecv79nBGGE0/AhUpeBRovPoL5j3LXlMeXd8gOw+NUAUqMYLTcpdE3LGmOgQpjCE0MqRPudY5zqsZCQ+wkUzhbzg25db8rdJOKMG0ESMlWzm/6kq/nZD5c/u4ntn7+/ZZIRNx6nlWwQM1qii1Ryx/+MvynwTvy5aoEttbll6dudqFlPnN4cnvI1Y5JcBna/eqTY+KDOByDhUSAsC/vL2cv/uZy6EQ70HA3K9BBeucEjUvSAS1GPHp/XE0n3PtqSzzmvZ+p9ExQ+n0v6De/40CTgftpiy4q4XUryQlus0jUZAZrEkh
  template:
    metadata:
      name: github-oauth-client-secret
      namespace: openshift-config
