apiVersion: v1
kind: Service
metadata:
  name: smartctl-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: smartctl-exporter
  ports:
    - name: metrics
      port: {{ .Values.port }}
      targetPort: metrics
      protocol: TCP
