apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartctl-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: smartctl-exporter
  endpoints:
    - port: metrics
      interval: {{ .Values.scrapeInterval }}
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
