apiVersion: v2
name: nfs-csi
description: NFS CSI driver and StorageClass for Synology NAS
version: 0.1.0

dependencies:
  - name: csi-driver-nfs
    version: 4.13.4
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
