csi-driver-nfs:
  controller:
    replicas: 1
    runOnControlPlane: true
    dnsPolicy: ClusterFirstWithHostNet
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  node:
    dnsPolicy: ClusterFirstWithHostNet
    tolerations:
      - operator: Exists

nfs:
  server: 192.168.1.2
  share: /volume1/kubenfs
