# Upstream SCCs from rook/rook release-1.19:
# https://github.com/rook/rook/blob/release-1.19/deploy/examples/operator-openshift.yaml

# SCC for Rook operator and Ceph daemons (mons, OSDs, mgr, rgw)
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rook-ceph
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostPID: false
allowHostNetwork: true
allowHostPorts: true
priority:
allowedCapabilities: ["MKNOD", "SYS_ADMIN", "NET_RAW"]
allowHostIPC: true
readOnlyRootFilesystem: false
requiredDropCapabilities: ["All"]
defaultAddCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-system
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-default
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-mgr
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-osd
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-rgw
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-nvmeof
  - system:serviceaccount:{{ .Values.namespace }}:default
  - system:serviceaccount:{{ .Values.namespace }}:rook-ceph-tools
