apiVersion: v2
name: rook-ceph-operator
description: Rook-Ceph Operator wrapper chart
version: 1.0.0
type: application
dependencies:
  - name: rook-ceph
    version: v1.19.6
    repository: https://charts.rook.io/release
