apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
  namespace: {{ .Values.namespace }}
data:
  config.json: |
    {
      "distSpecVersion": "1.1.0",
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "info"
      },
      "extensions": {
        "search": { "enable": true },
        "ui": { "enable": true },
        "mgmt": { "enable": true },
        "sync": {
          "enable": true,
          "registries": [
            {{- range $i, $url := .Values.syncRegistries }}
            {{- if $i }},{{ end }}
            {
              "urls": [{{ $url | quote }}],
              "onDemand": true,
              "tlsVerify": true,
              "content": [
                { "prefix": "**" }
              ]
            }
            {{- end }}
          ]
        }
      }
    }
