apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: monitoring
  labels:
    name: longhorn-prometheus-servicemonitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-exporter
  namespace: monitoring # namespace:cluster
  labels:
    team: rook
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-exporter
      rook_cluster: rook-ceph # namespace:cluster
      ceph_daemon_id: exporter
  endpoints:
    - port: ceph-exporter-http-metrics
      path: /metrics
      interval: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: monitoring # namespace:cluster
  labels:
    team: rook
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph # namespace:cluster
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 10s