---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:1.5.1
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
                path: /login
                port: 6767
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 60m
              memory: 256Mi
            limits:
              memory: 500Mi
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /data
            name: data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bazarr-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  ports:
    - port: 6767
  selector:
    app: bazarr

---

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bazarr-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "bazarr.homelab.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bazarr
spec:
  hosts:
  - "bazarr.homelab.net"
  gateways:
  - bazarr-gateway
  http:
  - route:
    - destination:
        host: bazarr
        port:
          number: 6767