
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - node2
      containers:
        - name: bazarr
          # envFrom:
          # - configMapRef:
          #     name: prowlarr-config
          image: ghcr.io/linuxserver/bazarr:v1.4.2-ls241
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
                path: /login
                port: 6767
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 60m
              memory: 256Mi
            limits:
              # cpu: 500m
              memory: 500Mi
          securityContext:
            # allowPrivilegeEscalation: true
            # capabilities:
            #   add:
            #   - NET_ADMIN
            privileged: true
          volumeMounts:
          - mountPath: /config
            name: config
          - name: data
            mountPath: /data
          # - name: tty
          #   mountPath: /tta
        #   readOnly: true
      # restartPolicy: Never
      # terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bazarr-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc
      # - name: tty
      #   persistentVolumeClaim:
      #     claimName: bazarr-config-pvc-bazarr-0
        # name: tunnel
      # - hostPath:
      #     path: /etc/localtime
      #     type: ""
      #   name: localtime
#         volumeMounts:
#         - name: mysql-persistent-storage
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql-persistent-storage
#         persistentVolumeClaim:
#           claimName: mysql-pv-claim
---



# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: bazarr
#   namespace: media
#   # annotations:
#   #   cert-manager.io/issuer: ca-issuer
# spec:
#   ingressClassName: cilium
#   # tls:
#   #   - hosts:
#   #     - bazarr.homelab.net
#   #     secretName: bazarr-homelab-cert
#   rules:
#     # - host: bazarr.homelab.net
#   - http:
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: bazarr
#               port:
#                 number: 6767

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: media
spec:
  ports:
    - port: 6767
  selector:
    app: bazarr
---



# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: bazarr
#   namespace: media
# spec:
#   selector:
#     matchLabels:
#       app: bazarr # has to match .spec.template.metadata.labels
#   serviceName: bazarr
#   replicas: 0 # by default is 1
#   # minReadySeconds: 10 # by default is 0
#   template:
#     metadata:
#       labels:
#         app: bazarr # has to match .spec.selector.matchLabels
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: kubernetes.io/hostname
#                 operator: In
#                 values:
#                 - node2


#       # terminationGracePeriodSeconds: 10
#       containers:
#       - name: bazarr
#         image: ghcr.io/linuxserver/bazarr:v1.4.2-ls241
#         ports:
#           - name: http
#             containerPort: 6767

#         readinessProbe:
#           httpGet:
#               path: /login
#               port: 6767
#           initialDelaySeconds: 10
#           periodSeconds: 15
#         volumeMounts:
#           - name: bazarr-config-pvc
#             mountPath: /config
          
#           - name: data
#             mountPath: /data

#           # - name: downloads
#           #   mountPath: /downloads
#           # - name: "render-device"
#           #   mountPath: "/dev/dri/renderD128"

#         resources:
#           requests:
#             cpu: 100m
#             memory: 400Mi
#           limits:
#             cpu: 1000m
#             memory: 1000Mi
#         securityContext:
#           # allowPrivilegeEscalation: false
#           # allowPrivilegeEscalation: true
#           # capabilities:
#           #   add:
#           #   - NET_ADMIN
#           privileged: true
#         # nodeSelector:
#         #   kubernetes.io/hostname: node3
#       volumes:
#       - name: data
#         persistentVolumeClaim:
#           claimName: media-data-pvc
#       # - name: downloads
#       #   persistentVolumeClaim:
#       #     claimName: downloads-data-pvc
#   volumeClaimTemplates:
#   - metadata:
#       name: bazarr-config-pvc
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: local-node2
#       resources:
#         requests:
#           storage: 10Gi




