
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: media
spec:
  storageClassName: longhorn
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          # envFrom:
          # - configMapRef:
          #     name: prowlarr-config
          image: lscr.io/linuxserver/sonarr:4.0.6
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
                path: /login
                port: 8989
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 300Mi
            limits:
              # cpu: 300m
              memory: 1000Mi
          securityContext:
            # allowPrivilegeEscalation: true
            # capabilities:
            #   add:
            #   - NET_ADMIN
            privileged: true
          volumeMounts:
          - mountPath: /config
            name: config
          - name: data
            mountPath: /data
        #   readOnly: true
      # restartPolicy: Never
      # terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config-pvc
      - name: data
        persistentVolumeClaim:
          claimName: media-data-pvc
        # name: tunnel
      # - hostPath:
      #     path: /etc/localtime
      #     type: ""
      #   name: localtime
#         volumeMounts:
#         - name: mysql-persistent-storage
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql-persistent-storage
#         persistentVolumeClaim:
#           claimName: mysql-pv-claim
---



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: media
  # annotations:
  #   cert-manager.io/issuer: ca-issuer
spec:
  ingressClassName: cilium
  # tls:
  #   - hosts:
  #     - sonarr.homelab.net
  #     secretName: sonarr-homelab-cert
  rules:
    - host: sonarr.homelab.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  ports:
    - port: 8989
  selector:
    app: sonarr
---



# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: sonarr
#   namespace: media
# spec:
#   selector:
#     matchLabels:
#       app: sonarr # has to match .spec.template.metadata.labels
#   serviceName: sonarr
#   replicas: 0 # by default is 1
#   # minReadySeconds: 10 # by default is 0
#   template:
#     metadata:
#       labels:
#         app: sonarr # has to match .spec.selector.matchLabels
#     spec:
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: kubernetes.io/hostname
#                 operator: In
#                 values:
#                 - node2


#       # terminationGracePeriodSeconds: 10
#       containers:
#       - name: sonarr
#         image: ghcr.io/linuxserver/sonarr:4.0.2.1183-ls230
#         ports:
#           - name: http
#             containerPort: 8989

#         readinessProbe:
#           httpGet:
#               path: /login
#               port: 8989
#           initialDelaySeconds: 10
#           periodSeconds: 15
#         volumeMounts:
#           - name: sonarr-config-pvc
#             mountPath: /config
          
#           - name: data
#             mountPath: /data

#           # - name: downloads
#           #   mountPath: /downloads
#           # - name: "render-device"
#           #   mountPath: "/dev/dri/renderD128"

#         resources:
#           requests:
#             cpu: 200m
#             memory: 600Mi
#           limits:
#             cpu: 500m
#             memory: 1500Mi
#         securityContext:
#           # allowPrivilegeEscalation: false
#           # allowPrivilegeEscalation: true
#           # capabilities:
#           #   add:
#           #   - NET_ADMIN
#           privileged: true
#         # nodeSelector:
#         #   kubernetes.io/hostname: node3
#       volumes:
#       - name: data
#         persistentVolumeClaim:
#           claimName: media-data-pvc
#       # - name: downloads
#       #   persistentVolumeClaim:
#       #     claimName: downloads-data-pvc
#   volumeClaimTemplates:
#   - metadata:
#       name: sonarr-config-pvc
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: local-node2
#       resources:
#         requests:
#           storage: 10Gi




