---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vpn-creds
  namespace: media
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgAsCfg4XR7EBTJU0TfJkNMaYMi9Oz5dMHQ9KT3krt8cq4a0cWKeCTAwawd0uWlyzNox9tJddiIFY1KZbAxsbSVDDA+Lu0hyF2XdvabqmzNLUoQjYio9tTFs7Brrelf7U1l9jvc6NaqmV08/Sc6QoikaGusSyKzCtFqvXWacdA1/8NBoT6bJjNLqAaUHJT4traTLRn/41v1UFDMi2q3l2D46o492tLs30MplzbXeyo4znTtVWbP+d1GKoc6t39FL/qSr1QEkAGG4uRVKGv4KUSracCpLwARbh+SDoeflpVYwqZVQmYHw2wAbVKSWr+YKlHPQqA7IL75wmMQgUPNvKhpDLm+pi5/tPd+bkyInFnQxEXMae9pGTt8QapzUp0DqWnE7LjGmteHW1Fpy+/U9G/W2JJO85EfsUaQkEXL5ADSD/KKetPjGQplfKTcYZXYywwSqTShFkx7HhYYb9eu1O8+S8OtVYNy8fUDTfUc7Ed44IttPfs/UKY2oKowGz0ZILRNB+MHJjjg/yZFQihC0gGWqnjH+xL4EDGuUeo6d0uf3VOxmXDWHIeGRX8FLDZF1dNjx5y1W/mFI98eoXBj34H0JSzE7l5vUbDiwWUPFDGwO198Y8iJVxTb0+0xZfFr25ZwXveppQp63RlOXhCMR6DhH753GbuRzX3rwABDH35b8G7H27YPC4OoN0lvBUrgH1LYRF0tyHDaKRrrga+iyc9Sw09EulcbPXDs=
    OPENVPN_USERNAME: AgCdIMGv5EZbx3HOJCUTq2wJ4PgQXpfgIvB0EaG7HRia9bBVDvxkWRzcJwZj8SatReCckoBI0lyGzlQ7tE+2MTVI9wzxm1vaAF7h1avmv4BlcvfkokZ69WBho6cCO0qM8wrxRGVKbuXbF/aOcZFZAh2kTy2a89JkssBPBxfAyVoRVcxT+IioiVZ5Y3QLVCtQZy72h8U2DckUfGzH+xCIvCJ0yM870CTiwDoHPodvh9+GetpkxPlYwnScSGaxixfdyIYd5xbZVqNq05Bdf5ajUBD7PQWElfWjX6vITp0sWoQ20YujCKnQ16VyYkCei+U2MPBG9YXwwtm+ztNvmjbY3KHEsb6kAz7DJsADBuc0tHjlqSaKDXBJhzKzeTeyj/n+W0TCa1d+6JOtOGix+1Phx3HXzbHinbrgJ92uhaL9rS1vdgjKWnlDEq2cab4xZBVk1CzInMgQXOCOqeDMsXtfqrH7J6l8WjveJv1vHC9SHwWXbe/l+nDVeRUZIZqHdXLHJUsDB4O/ZBnuhUEgYfYwYHLdqDPp+9RAFW4UIUM6IJyatyYthqIsPm8yVos37gYiz0IcMjJSmy2azYxbzUvXYk3xfx6tvpPDbevMBprUPpoI3M3Zt58S2C+xVMLHFCT/cUtSvDudKQucLWaeAZvTJVyqG7cdfQCWKwRMK8v3qpTvY/CROz9Bwdq47S7UFXDTQJbTjH5JggdDHyvP8kfRB1ueMJHpKeuSDQg=
  template:
    metadata:
      name: vpn-creds
      namespace: media
