---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vpn-creds
  namespace: media
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgDPOUnKEiBU3mpOGVIYYh+8Zmjd11OfEiArYZUxTgxRm8ZJ5RxWfn9/87nc1ApGpHdKVIxFKa4ZJczuJOXzpVIEqpsTsiAKp4wzEqBncx4eA4zjwa/ainB3HxgPha4D7HAea3dzIFJRHPuhcW2a1XASgRckvfkGcEVH3SE4yX/3lZOJLA1EVGIhwxn6kjlhW8LOVcuS5THqXD/qQs2f/psxzCwECxYbVP6c5ZzVMi2xnbTHRxJIZortUHoge2986gEenqbGjG0hpy4RJ6pXBEknMLMPtblYbuy0zj/mmUeL5B9z8oP4Bw03O+Dzp0PF4Crdh4T8iM+C+GEYVlMEWxanmEMSeIrpE+oRyOdSrXOr+XqhppuWsI5KHlsKIDu2h/r/STVfWevzFAY6h+nKE2W3n6fMSqNHyESLjwDKjDFsoIiliSsnxiLd1G9IIryr86nZiIS/zmRemfBwBAUfPpt5PErB8fX3qizNGOfYnvqxFUxFqKwK5yoLx6zRRkrIyCTNNe/C2cXz7oB1pf5rmr4jEKjg052BRPCHEhu3p2jFn+0EmaJMLnofkvfbF1bW7bg3G04B8dhSRApYbnA2wQsiW60pr+TXlB9b9aWFvI5jY3IK062rzl/bUVJbTDsvS5e+43D4LIIqazD1M8xOGV9J/uvRG0AVnNsiz7/d1pkXY11LZS6ZHkTWugwb+xDb+oUUpFXoV+kh7Z5aRT9XTY8CbnzfnNHw5ek=
    OPENVPN_USERNAME: AgBKxaodjbEuWkDcQoMZ4c4TCv6KL1szpusxDF8X5UBPBdstEeBSAP2mHrR1RfBAjJoOkQZ+idPXaZHmrSseqCcICbPjy2pXQk0TS3BXkKvar+9Q3LFpv0Fsrako0/36JARW79hi5RWB7wpDse9d8Tr8pJtKnQngzhHrFaU8ORMYQjm4Ka6n6qNU344C6ydh1eSlPS2jcCsj9GYlGpFCnoDxGn4rsS7nkXXdGwVBDWAAfSPPTZb0rvNcxfZEr8Wf48UXiikfhZNOMJtdFFbiVfFpPVZtC/slLRIwBXzBeo4kI2/tABtvDySFlD84Fc2qNf+P4s0SlvsjIUPXGWGltBqMjOKh/Uf3xG0WxVSvD68yuvU1ATj98xf5MBtGJazOTNw8g2rTDCopD7Z1bzVXS0MN9u/3qyyJB7GCCY7IeiTjl7kPYsmSj/OwIt0d/dH9+HFaphCaU/CcEZDQhBLQmTzQcx+m4//EWlZvdZaqrmD7ESjlYxEMa8HWcAopLQ3YRVGBfcFc164TMaccwarU0Ou5N6ZUZHa0+nBrpkCB28zJHJwaKfkv/GphgAsj8MIgP1ycT8jjU5VRe1dPg/Oajcp22NlYyyNkYWh9KcRZZkeA1tIMyU+LK7NuhkfO6R8QCymEb/iIlLHbwobNsbaFc9tR6Vb2Kxp44BUOiZlNAOqsX62k9/5QZRiiyI1fn/0LQkMpeztAMngCPuVJMQaU4ckSAQj340/+JVo=
  template:
    metadata:
      name: vpn-creds
      namespace: media
