apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-csi-scc
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["privileged"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfs-csi-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-csi-scc
subjects:
  - kind: ServiceAccount
    name: csi-nfs-controller-sa
    namespace: nfs-csi
  - kind: ServiceAccount
    name: csi-nfs-node-sa
    namespace: nfs-csi
