apiVersion: v1
kind: Secret
metadata:
  name: cnpg-pull-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30=
