apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keepers-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.sharedData.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharedData.size }}
