---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vpn-creds
  namespace: keepers
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgA5Ycv0h4IdgC4ctdaXcQYCWTuLmJt/Wr+o+FYmGoszXFaCzQygEGu73KP4VV0gCWidBRfyuOXeW51aAe9eLK+GnVETsomgbxUhZbDEYDulmUW68BSCPXbeOyOOD5yfQRLjPmh3KVeFg6ci8YDdoxA0EQm0LxdxPZq0lRSYB3cV5m0Nle6NT02FxmWp0Gqmby1WlMhaU1580126b3DfCb2jwUhXme2p3vAwlg5DcAqYJfTmnnxrSgwOmPVhe9F84I0mRPY0i2wdX5LugGJPC98TznQ4S4hRkKxv1gPt8SZUEqynpeXtxR/MiRXcv3gbLVYfeyohU2jNFXD4o8auQFsLllNWFjTLsIqiuyIc/w/btL95fDijeXpGxbchFVjOoQnk6d1oxAIvz++WgaRvxnCprH/bXdHq/aj9VKM/ThflIjuZtn+v5KTTdUo4/T6eXAQpzmCH/4Uqb2cYJ8mTqpvYYPbxsPO3q7/s+bYKNI3d/PW0G0qcZ8UH560KlHqfV7IJZRuSAwQRyeZtCMqLDSlhBrZh2EhNaTK42FIvXjSvv78igymgq07zQnqiYjjLS19P1MJxz6uqLYk0i0PsPXhAIvPER5u4OTBtJlHkHTZakI7EAsUDWq6Mjsm33DVaKH3ceBrndEC8t8N+UpRS5Sc66x6ZhYh9rKyntjEMT10nZXJrQfJHBRQnEz7CjXMvW45El+ByyYu/tkTbLgkekG2dhfxulzSsdyk=
    OPENVPN_USERNAME: AgBgitsN9tRUkYqZwmBAHh0h/e15Qgerb5FusD5WSejI4bQzH0oDWH4Zvnn2qkdhI5ZZwpJmQ0EmXbKVwp/X1npb6MtQnLjY4harCADGqZQhBBxdwo19Al78vP8Vvb+K9LPfepPzq0o+KWZBGDxgji+dyJRCzrU+zgD5KZY/rR0OoqElDPzl+cp8Vfe+X+LXCnvutxvnqhjNVAMJvfs0qj+qntB4Vvvzd9OR9k0os4SruxlIkldtNavk7NrwA8+lkeSmAPxsjnGzO80H1fCTSLna72fE5lnETNDwrKqn1EsD8GdZVPTToJ+ea0KJpB3SP9BYowFYm7nAlUir54xk3X5YtXl6jcL3FUuNO7vPCmbi1Vt1K7fRrFLJ1ZfrShvuGYMrquaG2yWq4zFWF5OWCzEotf3oaCKNmHz2+BUdOxc6jM7FKZJ5FSL1mCAriqo58xLaGGgaM2OJKWgVN8FZ7pkIOHMANcISh9bpHhHYq7q3FLXZ0kcZf4CDIk5ZIPVKUJu/rWlyqDgOzhQYI0fRJG+gr1k/DbMxVP/kV7ssgUPObSQ1CILaSV20x/a301EQOD4ACZf0kZCJq4LMYprmoPqg8v1FEh1K9PT7GkICE1IBMCsfAB8I+2/Yz/j9GiVUvdmdDLNKhGZL0TPh/S6bEMLLBgrgMLAWrteOrAVE5SuflUi28OYCgO+OiuTOd5iazYHTl5AMK/4EFVNADUbusRp0edg+NczfNns=
  template:
    metadata:
      name: vpn-creds
      namespace: keepers
