{{- range $name, $cs := .Values.catalogSources }}
{{- if $cs.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ $name }}-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: {{ $cs.image }}
  displayName: {{ $cs.displayName }}
  publisher: {{ $cs.publisher }}
  updateStrategy:
    registryPoll:
      interval: {{ $cs.pollInterval }}
{{- end }}
{{- end }}


