---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: grafana
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgAVObo89sNG/NeqEkuNs+vqO48G1ICZJWGO852jDVLz1RzOt/aK06Ugn55a29Gacc5am7mtyT2WDMLUl8Jy5EZrmeFLz2L1zr5Cy1FnL1Ig29IPUIB92Qf8WozziLOVepJUtPBqkIKTQ7kqdSRkz7xbis3a14Iz9P9WxkvU1FuXkAkdV/z86f7HuOM+W6LWSuaORxCMTwp+Jmk4tcqiLKx1Pq92/Wdx6aI4n782UfmdbEvT4P+qKA0PnQ0BRqNroo0H2/seAd5dv56m/DvN9i+fC+s+gE7aKXXU6b7eKqbeL/OIFH8+vBr661XpGhAXphAW8jDhQWJTfd8G5x3m+IYe8GyMTDQTiQPVnc6bv59en9VQjKVcj4j7M4j3elWZfA17HcDECnTiDQRNK/Zpd5Z/sICj6HDq+UaZRoxAa4h94w+bviRgTgBsrUxbdX0dcV5yW7q41DinAfYEBXM7LmRoOy/v7wHAdd6CYF5Co2+46/5UyR41hVa2oTojbJJHbgpliD/GzZPY2bhjxPHmADi9E4OA0gXKpwyIXrMbX9svlaQsZiq/3QMFNXII75u1Qbgt/czPNGTyhrcndT9tYzStsN1GanMRUq1yNJBOoEht21i6muhNecWob4z7i14TICmj6Y6z6gN8jAxaWYOwuv8IpXYXUO26qmq2xhvSrbGJEvyQ/u3h5flY424o0ZlawpGTHggvZWOAtLuzWFiRN7mZvot7Pw==
    GF_SECURITY_ADMIN_USER: AgC33UcJaDYhehO2P6Lieqj9VD1DhEa5LSDCjzd91ZClX1BuV16pOTWbShBPNTbXRgxxsLTOcNHUGsn5x1ohq4kW2OrttFzoEQwNd7hcBmv091hXpA/UpIEXkmj99BPcg9KI50oVlIKXu4hue6gsCRcfFwP63ayByDXZ95hf83yklelXzGocasKqV4tLdJgvaUNTL597GPCfZQ7BssIj5UhsyiXW/kx53+ilOiprcV1NttYT3AFH0/vDtxorbNus48FMpwKjkRGS78HzugCx08j2gz/Z/RvJOouwsgFC4KbWedoAHMOAiLpw0bL4hBHNBJdyfbvM+dZRNQC0m0oeTU2cmQsSX6awZuu+59RuG05uLD9AeBUODrdLsDSK8dVhFqLBHvh6amPp5Pl1vJC8g10ph5yU72rFDVRu0JtSY/ymrK+O6epiDUVPWKAOKJmCecrgIB1hqt4cdIULGX8PaQ6w4VgrIVJVhNcy9AfViF9xZrS5m28gRIQgFNjdUw4mE7np3btr8/dRiyMiF0ERDNEPLkokKJEOYcc9Nih4czPrBSEhmzuWLly8ERDaxH61BTykHFj2+y8f9kAgEqeIVWy95KUYGae9a3K9jJ6WQ4i5PzVdz+qX563QSH+gyGraWXk8oncZLtjmVyTB8SWxn3doNClzbGRDuqt0fszlm3rvFst+0R+JPK2gOi0yc+ONoAg4RigeiA==
  template:
    metadata:
      name: grafana-credentials
      namespace: grafana
