{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gatus
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: gatus
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
