apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gatus
spec:
  selector:
    app.kubernetes.io/name: gatus
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
