---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dsm-credentials
  namespace: synology-cert-sync
spec:
  encryptedData:
    password: AgB6HFrXoBwoyadyNAv96i14UZjKTRDBB/qGcpx02pyW1ItRdbm3cS4ZB90mBDoMDZprCEsYHpRTqddRe/wDO0G2M9KvKUaM8n3PSfd6Ej9sFZ8QPsVH5yUXJNXrMCRf0SIGKgMnBqV0IYfvGHI74yvdtsHONUcj1eqQezrpcJC2faCPHS/pmOmUXK1BHmNR5+dGwiuBNGNOOrqVEOGaEUDAjNqFRW77avmaV0UsjTKhHjIiYWp4BJisYkOTM2i2UEjwtUMS/Aj1RTRErVosbT1Bj98X3aCPytnz3JmXcwPXorYPjQxTcRl2WU/dH2XVeH/aTHDpxn1DZpu3DsDkyYaOECudS7r0jPj5vkMTFgqS7K2vHG3hILuazRvOggksk8gXqAGWMkvHq78V5Z+ooWbXyxLd3BITOz0dKkyO0KKP5MFX0YtOiOjfEQB1haMSiOZon9qZFhi0zOoWVdV8jXe3f5DEOUux5mIwEz9P4IGpbQ+ju1Sn4kaN1kEE74wvQ7+5TUImKJh+S8H1q2P9sD4Z70xLZwx0Bk94nFr+p1r/YDt5/LO6u2BrSH21c1C7hGhBszXYRA72G9eaIijveUrSvr8yXhUUWALb+MuOtH6Il9yaalTaYVHM/i3lRKiOYa3TuDckzGOcgFqSitXnk3n5E8mltp/rPgQQLNQ62Lb17Q2gp6m73qzx2rgLHm+me83hibKrWIujP3ma/2x+6OI3Rhpy+g==
    username: AgBqi9eaeIe1b9iGIMYK3pfd6UgWd1HscTwXv6pBu0gJOHM80JzszSHK+frM3PFYyP4FUWA3QG5aSxrX8CmqL5fDc16dng8itgaCbohWMd5g8/63q5f6OFmr4vJY6j6qd160tpvJc7wATs0wJxBPFqH2J8Ynbbv8vb8b8oukSvdI9sCwYDBvc7/4VXAR++a2eOyEreR71E9qSwNnu2/VTfpHH9/fz7TI61onR9KYdP41/CHyvWrG1LrxKdwJanBSRfilkN5Gxy9Hr8jGDbUQK6JR6x7O0Zdrr0KDIN0ChC7qYqPeU/nGeKInLB0q1y64JJE3mfnBxsOsL+HFQZQfFYLjHpzLifubggatAH3B68Gf1c8leH0ScyXQxPP61SQMuS4Q175uljgWCZIbCxkNNwDTHD60J+JiikWqkV40NWVn3ngVB+4UpFJY5uUc5KQ2tmfxODSrgMLQvSE2nEFgsHoufavNzAcUhYNsMv4RTKTQmM9NvFp/F4wDHGHPo/w5CUYM5DEuGDRKr+JUMM0wmqyZHfchjN7F7W4OxPHceaJM7ano0wjLxNwA7kSuJxDZbht7k35DBvg4bHGyam1x56J6FdrcbclxwYcCRcUMey0O+m6NogCWL5NYG9Ak+oAsZ0k8B0vD9/fy61lfKiNstS4nGXRQJJc6KwQvQaN+JdxmGB/N0QP7TnhgpK+H+1BWCk0ZUfjem3RG1fNNFlsOkFC+
  template:
    metadata:
      name: dsm-credentials
      namespace: synology-cert-sync
