apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  schedule: {{ .Values.schedule.cron | quote }}
  paused: {{ .Values.schedule.paused }}
  template:
    ttl: {{ .Values.schedule.ttl }}
    storageLocation: default
    snapshotMoveData: {{ .Values.schedule.snapshotMoveData }}
    defaultVolumesToFsBackup: false
    includeClusterResources: true
    {{- with .Values.schedule.includedNamespaces }}
    includedNamespaces:
{{ toYaml . | indent 6 }}
    {{- end }}
    {{- with .Values.schedule.excludedNamespaces }}
    excludedNamespaces:
{{ toYaml . | indent 6 }}
    {{- end }}
