apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rook-ceph-rules
  namespace: rook-ceph
  labels:
    team: rook
spec:
{{ .Files.Get "files/ceph-prometheus-rules.yaml" | indent 2 }}
